# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190301_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentexit',
            new_name='Student',
        ),
    ]
